[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "build123d-examples"
version = "0.0.1"
requires-python = ">=3.8"

dependencies = [
  "build123d @ git+https://github.com/gumyr/build123d"
]


[tool.setuptools]
py-modules = []


